# Generated by Django 6.0.5 on 2026-05-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_address_alter_client_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
