# Generated by Django 6.0.5 on 2026-05-25 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_employee_birth_date_remove_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='+375 (29) 000-00-00', max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +375 (29) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
