# Generated by Django 6.0.5 on 2026-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employee_birth_date_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='show_on_contacts',
            field=models.BooleanField(default=True, verbose_name='Показывать на странице контактов'),
        ),
    ]
