# Generated by Django 6.0.5 on 2026-05-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee_show_on_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
